version: 2
jobs:
  build_gcc:
    docker:
      - image: thoughton/gcc-cmake:latest
    steps:
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: bash build.sh
      - run: ./build/test/LibMVC-test data/frb30-15-mis/frb30-15-1.mis 420 450 5
  coverage:
    docker:
      - image: thoughton/gcc-cmake:latest
    steps:
      - run: apt update && apt install lcov -y
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: bash build.cov.sh
      - run: cd build.cov && make LibMVC-test-coverage
      - store_artifacts:
          path: build.cov/LibMVC-test-coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc
      - coverage

