version: 2
jobs:
  build_gcc:
    docker:
      - image: thoughton/gcc-cmake:latest
    steps:
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: bash build.sh
      - run: ./build/test/LibMVC-test data/frb30-15-mis/frb30-15-1.mis 420 450 10

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc

