version: 2
jobs:
  build_gcc:
    docker:
      - image: thoughton/gcc-cmake:latest
    steps:
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: bash build.sh
      - run: ./build/test/LibMVC-test data/frb30-15-mis/frb30-15-1.mis 420 450 10
  coverage:
    docker:
      - image: thoughton/gcc-cmake:latest
    steps:
      - run: apt update && apt install lcov gcovr -y
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: bash build.cov.sh
      - run: cd build.cov && make LibMVC-test-coverage
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: build.cov/LibMVC-test-coverage.xml
          prefix: coverage
  meson:
    docker:
      - image: ubuntu:latest
    steps:
      - run: apt update && apt install git build-essential ninja-build meson -y
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: meson build
      - run: cd build && ninja
      - store_artifacts:
          path: build/meson-logs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc
      - coverage
      - meson

