version: 2
jobs:
  coverage:
    docker:
      - image: ubuntu:latest
    steps:
      - run: apt update && apt install git curl build-essential ninja-build meson lcov gcovr -y
      - checkout
      - run: bash build.cov.sh
      - run: cd build.cov && ninja test && ninja coverage-xml
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: build.cov/build.cov/meson-logs/coverage.xml
          prefix: coverage
      - store_artifacts:
          path: build/meson-logs

  meson:
    docker:
      - image: ubuntu:latest
    steps:
      - run: apt update && apt install git build-essential ninja-build meson -y
      - checkout
      - run: meson build
      - run: cd build && ninja test
      - store_artifacts:
          path: build/meson-logs

workflows:
  version: 2
  build_and_test:
    jobs:
      - coverage
      - meson

